### ISSUE TITLE
[feature request] support compact and spaced class

### ISSUE THREAD

**Issue by setop** [matsubara0507/marp-themes#2]
Would be nice to have classes to make a slide more dense/compact or more spaced/expanded than normal to adjust to the content.

Sometime you'd like one more sentence fit on the slide by just compacting the content a bit. On the contrary when there is little content, you'd like it to take more room on the slide.

I had a theme that used :

```css
section.compact {
  line-height: 1;
}
...

section.littlespaced {
  line-height: 1.4;
}

section.spaced {
  line-height: 1.8;
}
```

I don't know if and how it could be adapted to work with "olive" theme that I like very much.

Cheers
